# Publish Documentation

on:
  workflow_dispatch:

env:
  HUMMINGBIRD_VERSION: "1.0"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: swift:5.9
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install rsync 📚
      run: |
        apt-get update && apt-get install -y rsync
    - name: Build
      run: |
        ./scripts/build-docc.sh
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/hummingbird-docs/${{ env.HUMMINGBIRD_VERSION }}
        target-folder: docs/${{ env.HUMMINGBIRD_VERSION }}
